compile:
	g++ UnitTest.cpp Prefix.cpp \
	../Postfix/
	../../COLLECTION/Stack/Stack.h ../../COLLECTION/Stack/StackExp.cpp \
	../../COLLECTION/Vector/Vector.h ../../COLLECTION/Vector/VectorExp.cpp \
	../../NUMBER/Operand/Operand.cpp ../../NUMBER/Romawi/Romawi.cpp \
	../../NUMBER/Arab/Arab.cpp ../../NUMBER/Logika/Logika.cpp -o TestPostfix
run:
	./TestPostfix